"""Tests for macOS LaunchAgent scheduler (M15.6 slice 1).

Two layers:

1. Pure plist generators — no I/O, no subprocess. Round-trip
   through ``plistlib.loads`` to verify the wire shape is what
   the system loader will accept.
2. ``install`` / ``remove`` orchestration — writes plist files,
   invokes ``launchctl``. ``launchctl`` is replaced by an
   in-memory spy via monkeypatch; tempfile-based plist paths
   are checked for atomicity (sibling tempfile + ``os.replace``).
"""

from __future__ import annotations

import plistlib
from pathlib import Path

import pytest

from yadirect_agent.services.scheduler.macos import (
    DAILY_LABEL,
    HOURLY_LABEL,
    MacOSScheduler,
    PlistInstallResult,
    generate_daily_plist,
    generate_hourly_plist,
)


class TestPlistGeneration:
    def test_daily_plist_round_trips_via_plistlib(self) -> None:
        # ``launchd`` parses plists with ``plistlib`` semantics.
        # Round-tripping our generated bytes through plistlib must
        # produce a dict with the keys ``launchd`` requires; a
        # regression that emitted invalid XML or a missing required
        # key would be caught here loudly rather than at the
        # operator's "why isn't my agent running?".
        executable = "/usr/local/bin/yadirect-agent"
        log_dir = Path("/Users/anna/Library/Logs/yadirect-agent")

        raw = generate_daily_plist(executable=executable, log_dir=log_dir)

        parsed = plistlib.loads(raw)
        assert parsed["Label"] == DAILY_LABEL
        # ``ProgramArguments`` is the argv ``launchd`` execs. It
        # MUST start with the executable path; further args are
        # the agent's CLI invocation (rule-based health, JSON
        # output for cron-friendly logs).
        assert parsed["ProgramArguments"][0] == executable
        assert "health" in parsed["ProgramArguments"]
        assert "--json" in parsed["ProgramArguments"]
        # Daily run at 08:00 local time.
        assert parsed["StartCalendarInterval"] == {"Hour": 8, "Minute": 0}
        # Output / error logs land in a predictable spot the
        # operator can ``tail -f`` to debug.
        assert parsed["StandardOutPath"] == str(log_dir / "daily.log")
        assert parsed["StandardErrorPath"] == str(log_dir / "daily.err")
        # ``RunAtLoad`` MUST be False (or absent) — we don't want
        # the agent to fire the moment it's installed; the schedule
        # owns the timing. A regression that flipped this would
        # spam the operator on every reboot.
        assert parsed.get("RunAtLoad", False) is False

    def test_hourly_plist_uses_start_interval(self) -> None:
        # ``StartInterval`` (seconds) is the launchd idiom for
        # "run every N seconds" — simpler than 24
        # ``StartCalendarInterval`` entries. 3600 = one hour.
        raw = generate_hourly_plist(
            executable="/usr/local/bin/yadirect-agent",
            log_dir=Path("/tmp/logs"),
        )
        parsed = plistlib.loads(raw)
        assert parsed["Label"] == HOURLY_LABEL
        assert parsed["StartInterval"] == 3600
        # Hourly check uses ``--days=1`` — wider window dilutes
        # the hour's signal into noise; narrower (less than a
        # day) ill-defined for daily-aggregated rules.
        assert "--days=1" in parsed["ProgramArguments"]

    def test_labels_are_pinned(self) -> None:
        # Operators and ``launchctl unload`` look up jobs by
        # Label. A typo here at upgrade time would orphan the
        # previous version's jobs in launchd's database. Pin the
        # exact strings.
        assert DAILY_LABEL == "com.yadirect-agent.daily"
        assert HOURLY_LABEL == "com.yadirect-agent.hourly-health"

    def test_executable_path_must_be_absolute(self) -> None:
        # ``launchd`` resolves ``ProgramArguments[0]`` relative to
        # the daemon's CWD (``/``), not the operator's. Relative
        # paths silently fail to launch. Reject at the boundary.
        with pytest.raises(ValueError, match="absolute"):
            generate_daily_plist(
                executable="yadirect-agent",  # not absolute
                log_dir=Path("/tmp/logs"),
            )


class TestMacOSSchedulerInstall:
    @pytest.fixture
    def fake_launchctl(self, monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
        """Replace launchctl with an in-memory spy.

        Returns the list of argv lists each ``run_launchctl`` call
        received. Tests assert against this rather than against a
        real subprocess.
        """
        calls: list[list[str]] = []

        def spy(args: list[str]) -> None:
            calls.append(args)

        monkeypatch.setattr(
            "yadirect_agent.services.scheduler.macos.run_launchctl",
            spy,
        )
        return calls

    def test_install_writes_plists_and_loads_them(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        # End-to-end: install writes both plist files into the
        # operator's LaunchAgents dir and invokes ``launchctl
        # load -w`` once per plist. The ``-w`` flag persists the
        # job across reboots; without it, ``launchctl unload`` at
        # the next ``schedule remove`` would leave the entry in
        # launchd's override database, breaking subsequent
        # installs.
        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )

        result = scheduler.install()

        assert isinstance(result, PlistInstallResult)
        assert (tmp_path / "LaunchAgents" / f"{DAILY_LABEL}.plist").exists()
        assert (tmp_path / "LaunchAgents" / f"{HOURLY_LABEL}.plist").exists()
        # log_dir created on demand — operators don't pre-create
        # ``~/Library/Logs/yadirect-agent`` and ``StandardErrorPath``
        # would crash launchd otherwise.
        assert (tmp_path / "logs").is_dir()
        # Pin: ``launchctl load -w`` called for each plist.
        assert len(fake_launchctl) == 2
        assert all(call[0] == "load" and "-w" in call for call in fake_launchctl)

    def test_install_atomic_via_os_replace(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # Same atomicity contract as ``BusinessProfileStore``: a
        # partial-write crash leaves the original (or no file) —
        # never a half-written plist that launchd would reject.
        import os

        replace_calls: list[tuple[str, str]] = []
        original = os.replace

        def spy(src: str | Path, dst: str | Path) -> None:
            replace_calls.append((str(src), str(dst)))
            original(src, dst)

        monkeypatch.setattr("os.replace", spy)

        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        scheduler.install()

        # Two plists → two replace calls. Source must be a sibling
        # tempfile (not the final target — would be a contradiction).
        assert len(replace_calls) == 2
        for src, dst in replace_calls:
            assert src != dst
            assert Path(src).parent == Path(dst).parent

    def test_install_creates_launchagents_dir_on_demand(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        # Fresh macOS account may not have ``~/Library/LaunchAgents``
        # yet (it's not created by default until something writes
        # there). Install must mkdir on demand.
        target = tmp_path / "fresh" / "LaunchAgents"
        scheduler = MacOSScheduler(
            launchagents_dir=target,
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        scheduler.install()
        assert target.is_dir()


class TestMacOSSchedulerStatus:
    @pytest.fixture
    def fake_launchctl(self, monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
        calls: list[list[str]] = []

        def spy(args: list[str]) -> None:
            calls.append(args)

        monkeypatch.setattr(
            "yadirect_agent.services.scheduler.macos.run_launchctl",
            spy,
        )
        return calls

    def test_status_reports_installed_when_both_plists_present(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        # ``schedule status`` for the operator's "is it set up?"
        # question. Reads the on-disk plists rather than asking
        # launchctl — same source of truth; status doesn't need
        # a subprocess (and tests don't have to mock one).
        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        scheduler.install()

        status = scheduler.status()

        assert status.installed is True
        assert status.daily_plist_path.exists()
        assert status.hourly_plist_path.exists()

    def test_status_reports_not_installed_on_fresh_account(self, tmp_path: Path) -> None:
        # No install happened. Status must report "not installed"
        # so the operator's ``schedule status`` after a fresh pip
        # install doesn't lie.
        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        status = scheduler.status()
        assert status.installed is False

    def test_status_reports_partial_when_only_one_plist_present(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        # Half-installed state (e.g. previous version had a typo
        # that left one plist on disk and the other missing). The
        # operator needs to see "installed: false" with both
        # paths so they can decide whether to reinstall.
        (tmp_path / "LaunchAgents").mkdir(parents=True)
        (tmp_path / "LaunchAgents" / f"{DAILY_LABEL}.plist").write_bytes(b"")

        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        status = scheduler.status()
        # Only a fully-installed pair counts as "installed".
        assert status.installed is False


class TestMacOSSchedulerRemove:
    @pytest.fixture
    def fake_launchctl(self, monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
        calls: list[list[str]] = []

        def spy(args: list[str]) -> None:
            calls.append(args)

        monkeypatch.setattr(
            "yadirect_agent.services.scheduler.macos.run_launchctl",
            spy,
        )
        return calls

    def test_remove_unloads_and_deletes_both_plists(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        scheduler.install()
        fake_launchctl.clear()

        scheduler.remove()

        assert not (tmp_path / "LaunchAgents" / f"{DAILY_LABEL}.plist").exists()
        assert not (tmp_path / "LaunchAgents" / f"{HOURLY_LABEL}.plist").exists()
        # Pin: ``launchctl unload`` called for each plist.
        assert len(fake_launchctl) == 2
        assert all(call[0] == "unload" for call in fake_launchctl)

    def test_remove_is_idempotent_on_fresh_account(
        self,
        tmp_path: Path,
        fake_launchctl: list[list[str]],
    ) -> None:
        # Operator runs ``schedule remove`` without ever installing.
        # No-op, no error. Same shape as ``KeyringTokenStore.delete``
        # / ``BusinessProfileStore.delete``.
        scheduler = MacOSScheduler(
            launchagents_dir=tmp_path / "LaunchAgents",
            log_dir=tmp_path / "logs",
            executable="/usr/local/bin/yadirect-agent",
        )
        scheduler.remove()  # no exception
